import "@repo/ui/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { Geist } from "next/font/google";

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

import Link from "next/link";
import { Button } from "@/components/ui/button";
import AuthButton from "@/components/AuthButton";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark"> 
      <body className={`${geist.className} antialiased bg-background text-foreground`}>
        <nav className="sticky top-0 z-50 w-full border-b border-border/40 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
          <div className="container flex h-16 max-w-7xl mx-auto items-center justify-between px-4">
            <Link href="/" className="font-bold text-2xl tracking-tighter text-amber-500">
              MOON<span className="text-white">RIDGE</span>
            </Link>
            <div className="hidden md:flex items-center gap-6 text-sm font-medium">
              <Link href="/packages" className="hover:text-amber-500 transition-colors">Destinations</Link>
              <Link href="/build-trip" className="hover:text-amber-500 transition-colors">Customize Trip</Link>
              <Link href="#" className="hover:text-amber-500 transition-colors">Blog</Link>
            </div>
            <div className="flex items-center gap-4">
              <AuthButton />
            </div>
          </div>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
